import {describe,it,expect} from 'vitest';
import {compileDepthSurface,migrateDepthSurfaceMeshing,type DepthSurfaceSource} from '../src/engine/depth-surface';
import {depthBoundaryBand} from '../src/engine/depth-boundary';
function source(radius=48):DepthSurfaceSource {
 const width=32,height=32,frame=radius*1.05,camera=radius*4;
 const depths=Array.from({length:width*height},(_,p)=>{const x=-frame+2*frame*(p%width+.5)/width,y=frame-2*frame*(Math.floor(p/width)+.5)/height;const d=radius*radius-x*x-y*y;return d>0?camera-Math.sqrt(d):0;});
 const mask=depths.map(d=>d?1:0),pixels=depths.flatMap((d,i)=>d?[i]:[]),anchor=(p:number)=>({id:`p${p}`,pixel:p,depthMm:depths[p]!});
 const fit=[pixels[0]!,pixels[10]!,pixels[100]!,pixels[200]!,pixels[300]!,pixels[400]!].map(anchor),validation=[pixels[20]!,pixels[120]!,pixels[220]!,pixels[320]!].map(anchor);
 const band=depthBoundaryBand({width,height,mask},2),used=new Set([...fit,...validation].map(a=>a.pixel));
 const edge=pixels.filter(p=>band[p]&&!used.has(p)).filter((_,i)=>i%11===0).slice(0,8).map(anchor);
 return {schema:'morphloom.depth-surface/0.2',id:'sphere',imageSha256:'a'.repeat(64),rawFieldSha256:'b'.repeat(64),width,height,samples:depths.map(d=>d?1/d:0),mask,camera:{projection:'orthographic-front',units:'mm',axes:'right-handed-y-up',frameMm:[-frame,frame,-frame,frame],cameraZMm:camera},calibration:{basis:'authored-fixture',fit,validation},stride:2,quality:{depthEnvelope:{status:'declared',nearMm:camera-radius,farMm:camera,toleranceMm:.001,basis:'authored-fixture'},boundary:{status:'declared',bandPixels:2,toleranceMm:.001,basis:'authored-fixture',anchors:edge}},primaryForm:{schema:'morphloom.sphere-front-constraint/0.1',radiusMm:radius,centerMm:[0,0,0],basis:'authored-fixture',centerFitToleranceMm:.001}};
}
describe('continuous declared sphere front',()=>{
 it('migrates without changing raw or existing candidate geometry',()=>{const before=source(),next=migrateDepthSurfaceMeshing(before);expect(next.schema).toBe('morphloom.depth-surface/0.3');expect(next.samples).toEqual(before.samples);expect(next.samples).not.toBe(before.samples);expect(next.meshing).toBeUndefined();const a=compileDepthSurface(before),b=compileDepthSurface(next);try{for(const k of ['position','normal','uv'])expect(b.geometry.attributes[k]!.array).toEqual(a.geometry.attributes[k]!.array);expect(b.geometry.index!.array).toEqual(a.geometry.index!.array);}finally{a.geometry.dispose();b.geometry.dispose();}});
 it.each([3,48,128])('creates a bounded front-only surface with analytic normals radius %s',r=>{const s=migrateDepthSurfaceMeshing(source(r));s.preview='declared-sphere-front';s.meshing={schema:'morphloom.depth-meshing/0.1',mode:'declared-sphere-front',maxSagittaMm:Math.min(.02,r/3000)};const saved=JSON.stringify(s),c=compileDepthSurface(s,{diagnostic:true});try{expect(JSON.stringify(s)).toBe(saved);expect(c.report.releaseAllowed).toBe(false);expect(c.report.candidate?.validationPass).toBe(true);expect(c.report.meshing?.maximumChordDeviationMm).toBeLessThanOrEqual(s.meshing.maxSagittaMm+.0001);expect(c.report.triangles).toBeLessThanOrEqual(100000);const p=c.geometry.attributes.position!,n=c.geometry.attributes.normal!,uv=c.geometry.attributes.uv!;for(let i=0;i<p.count;i++){expect(p.getZ(i)).toBeGreaterThanOrEqual(-1e-9);expect(Math.abs(Math.hypot(p.getX(i),p.getY(i),p.getZ(i))*1000-r)).toBeLessThan(.001);expect(Math.hypot(n.getX(i),n.getY(i),n.getZ(i))).toBeCloseTo(1,5);expect(uv.getX(i)).toBeGreaterThanOrEqual(0);expect(uv.getX(i)).toBeLessThanOrEqual(1);}}finally{c.geometry.dispose();}});
 it('rejects undeclared modes, unsupported old versions, holes and budgets',()=>{const s=migrateDepthSurfaceMeshing(source());s.preview='declared-sphere-front';s.meshing={schema:'morphloom.depth-meshing/0.1',mode:'declared-sphere-front',maxSagittaMm:.02};expect(()=>compileDepthSurface(s)).toThrow(/diagnostic/);expect(()=>compileDepthSurface({...s,schema:'morphloom.depth-surface/0.2'},{diagnostic:true})).toThrow(/0.3/);const hole=structuredClone(s);hole.mask[500]=0;expect(()=>compileDepthSurface(hole,{diagnostic:true})).toThrow();expect(()=>compileDepthSurface({...s,meshing:{...s.meshing,maxSagittaMm:.00001}},{diagnostic:true})).toThrow(/budget/);});
});
