import * as THREE from 'three';
import {describe,it,expect} from 'vitest';
import {compileAssemblyIR,validateAssemblyIR} from '../src/engine/assembly-compiler';
import {migrateReferenceProjectionOrientation} from '../src/engine/reference-projection-orientation';
import type {AssemblyIR} from '../src/engine/assembly-ir';
function fixture(direction='negative',flipU=false):AssemblyIR {
 return {schema:'morphloom.assembly/0.1',name:'projection orientation',units:'mm',components:[{id:'target',name:'target',category:'mechanical',materialName:'polymer',detail:'authored test',geometry:{op:'roundedBox',size:[40,30,10],radius:1,segments:3},material:{color:'#333333',surface:'molded-polymer',referenceProjection:{uri:'/test.png',mapping:'assembly-xy',crop:[0,0,1,1],boundsMm:[-20,-15,20,15],fingerprint:'a'.repeat(64),orientation:{schema:'morphloom.reference-projection-orientation/0.1',direction,flipU}} as never}}]};
}
function projected(build:ReturnType<typeof compileAssemblyIR>){let result:THREE.Mesh|undefined;build.root.traverse(x=>{if(x instanceof THREE.Mesh&&x.name==='target')result=x;});return result!;}
describe('declared reference projection orientation',()=>{
 it('keeps legacy positive geometry, UV, normals and groups unchanged without an implicit migration',()=>{const legacy=fixture('positive');delete legacy.components[0]!.material.referenceProjection!.orientation;const a=projected(compileAssemblyIR(legacy,'beauty')),b=projected(compileAssemblyIR(fixture('positive'),'beauty'));expect(a.geometry.groups).toEqual(b.geometry.groups);for(const key of Object.keys(a.geometry.attributes))expect(a.geometry.attributes[key]!.array).toEqual(b.geometry.attributes[key]!.array);expect(a.geometry.userData.morphloomReferenceProjectionPartition.method).toBe('source-facing-triangle-partition-v1');expect(legacy.components[0]!.material.referenceProjection!.orientation).toBeUndefined();});
 it('rejects null, arrays and undeclared fields before compilation',()=>{for(const orientation of [null,[],{schema:'morphloom.reference-projection-orientation/0.1',direction:'negative',unknown:true}]){const s=fixture();Object.assign(s.components[0]!.material.referenceProjection!,{orientation});expect(()=>compileAssemblyIR(s,'beauty')).toThrow(/orientation/);}});
 it.each(['positive','negative'])('projects only declared %s facing triangles',direction=>{const build=compileAssemblyIR(fixture(direction),'beauty'),mesh=projected(build),g=mesh.geometry,p=g.attributes.position!;for(const group of g.groups)if(group.materialIndex===0)for(let i=group.start;i<group.start+group.count;i+=3){const a=new THREE.Vector3().fromBufferAttribute(p,i),b=new THREE.Vector3().fromBufferAttribute(p,i+1),c=new THREE.Vector3().fromBufferAttribute(p,i+2);const n=b.sub(a).cross(c.sub(a)).normalize();expect(n.z*(direction==='negative'?-1:1)).toBeGreaterThanOrEqual(.05-1e-6);}});
 it('reverses only photograph-facing UV u and preserves hidden fallback UV',()=>{const a=projected(compileAssemblyIR(fixture('negative'),'beauty')),b=projected(compileAssemblyIR(fixture('negative',true),'beauty'));expect(a.geometry.attributes.position!.array).toEqual(b.geometry.attributes.position!.array);let changed=0;for(const group of a.geometry.groups)if(group.materialIndex===0)for(let i=group.start;i<group.start+group.count;i++){expect(b.geometry.attributes.uv!.getX(i)).toBeCloseTo(1-a.geometry.attributes.uv!.getX(i),6);changed++;}for(const group of a.geometry.groups)if(group.materialIndex===1)for(let i=group.start;i<group.start+group.count;i++){expect(b.geometry.attributes.uv!.getX(i)).toBe(a.geometry.attributes.uv!.getX(i));expect(b.geometry.attributes.uv!.getY(i)).toBe(a.geometry.attributes.uv!.getY(i));}expect(changed).toBeGreaterThan(0);});
 it('migrates explicitly without mutating legacy source or nested arrays',()=>{const projection=fixture().components[0]!.material.referenceProjection!;delete projection.orientation;const saved=JSON.stringify(projection),next=migrateReferenceProjectionOrientation(projection,'negative',true);expect(JSON.stringify(projection)).toBe(saved);expect(next.crop).not.toBe(projection.crop);expect(next.orientation).toEqual({schema:'morphloom.reference-projection-orientation/0.1',direction:'negative',flipU:true});});
 it('rejects unknown version/direction and nonboolean reflection',()=>{for(const orientation of [{schema:'unknown',direction:'negative'},{schema:'morphloom.reference-projection-orientation/0.1',direction:'sideways'},{schema:'morphloom.reference-projection-orientation/0.1',direction:'negative',flipU:'yes'}]){const s=fixture();Object.assign(s.components[0]!.material.referenceProjection!,{orientation});expect(()=>validateAssemblyIR(s)).toThrow(/orientation/);}});
});
