import * as THREE from 'three';
import { describe, expect, it } from 'vitest';
import { compileAssemblyGeometry, validateAssemblyIR } from '../src/engine/assembly-compiler';
import { createTubePath, migrateTubeQuadraticCurve } from '../src/engine/tube-quadratic-curve';
import { applyAssemblyComponentPatch, applyAssemblyComponentBatchPatch, fingerprintAssemblyIR } from '../src/engine/assembly-edit';
import { analyzeTopology } from '../src/engine/topology';
import type { AssemblyGeometryIR, AssemblyIR } from '../src/engine/assembly-ir';
const straight = (): Extract<AssemblyGeometryIR, {op:'tube'}> => ({op:'tube',points:[[0,0,0],[200,0,0]],radius:2,tubularSegments:32,radialSegments:12});
const fixture = (): AssemblyIR => ({schema:'morphloom.assembly/0.1',units:'mm',name:'two separate rails',components:['rail','untouched'].map(id=>({id,name:id,category:'mechanical',materialName:'steel',detail:'authored test',geometry:straight(),material:{color:'#333333'}}))});
const declaration = {schema:'morphloom.tube-quadratic-bezier/0.1' as const,controlPointMm:[100,40,0] as [number,number,number]};
describe('opt-in quadratic tube path',()=>{
 it('evaluates exact endpoints and Bezier midpoint in scene metres',()=>{const path=createTubePath({...straight(),curve:declaration});expect(path.getPoint(0).toArray()).toEqual([0,0,0]);expect(path.getPoint(1).x).toBeCloseTo(.2,12);expect(path.getPoint(.5).toArray()).toEqual([.1,.02,0]);});
 it('preserves the absent-option CatmullRom path, arrays and immutable opt-in',()=>{const source=straight(),snapshot=structuredClone(source);const a=createTubePath(source),b=new THREE.CatmullRomCurve3(source.points.map(p=>new THREE.Vector3(p[0]/1000,p[1]/1000,p[2]/1000)),false,'centripetal');for(let i=0;i<=32;i++)expect(a.getPointAt(i/32).toArray()).toEqual(b.getPointAt(i/32).toArray());const next=migrateTubeQuadraticCurve(source,declaration.controlPointMm);expect(source).toEqual(snapshot);expect(next.points).not.toBe(source.points);expect(next.curve).toEqual(declaration);expect(migrateTubeQuadraticCurve(next).curve).toBeUndefined();});
 it.each([.5,1,2])('generates finite closed outward-capped geometry at scale %s',scale=>{const g=migrateTubeQuadraticCurve(straight(),[100,40,0]);g.points=g.points.map(p=>p.map(v=>v*scale) as [number,number,number]);g.curve!.controlPointMm=g.curve!.controlPointMm.map(v=>v*scale) as [number,number,number];g.radius*=scale;const compiled=compileAssemblyGeometry(g),root=new THREE.Group(),material=new THREE.MeshBasicMaterial();root.add(new THREE.Mesh(compiled,material));try{const report=analyzeTopology(root);expect(report.pass).toBe(true);const p=compiled.getAttribute('position'),n=compiled.getAttribute('normal');expect(Array.from(p.array).every(Number.isFinite)).toBe(true);const path=createTubePath(g);expect(new THREE.Vector3().fromBufferAttribute(n,p.count-2).dot(path.getTangentAt(0))).toBeCloseTo(-1,5);expect(new THREE.Vector3().fromBufferAttribute(n,p.count-1).dot(path.getTangentAt(1))).toBeCloseTo(1,5);}finally{compiled.dispose();material.dispose();}});
 it('rejects malformed, closed, folded, excessive and singular declarations before geometry allocation',()=>{
  const invalid=[null,[],{}, {...declaration,schema:'unknown'}, {...declaration,extra:1},{...declaration,controlPointMm:[100,40]},{...declaration,controlPointMm:[100,NaN,0]},{...declaration,controlPointMm:[-1,0,0]},{...declaration,controlPointMm:[0,0,0]},{...declaration,controlPointMm:[100,100001,0]},{...declaration,controlPointMm:[100,1000,0]}];
  for(const curve of invalid)expect(()=>compileAssemblyGeometry({...straight(),curve} as never)).toThrow(/quadratic|Bezier|Unsafe numeric/);
  expect(()=>compileAssemblyGeometry({...straight(),curve:declaration,closed:true})).toThrow(/quadratic|Bezier/);
  expect(()=>compileAssemblyGeometry({...straight(),points:[[0,0,0],[0,0,0]],curve:declaration})).toThrow(/quadratic|Bezier/);
  expect(()=>compileAssemblyGeometry({...straight(),radius:300,curve:declaration})).toThrow(/curvature/);
 });
 it('sets/clears via version 0.2 and preserves source/unrelated parts with fingerprints',async()=>{const ir=fixture(),snapshot=structuredClone(ir);const a=await applyAssemblyComponentPatch(ir,{schema:'morphloom.component-patch/0.2',operationId:'bend',componentId:'rail',expectedInputFingerprint:await fingerprintAssemblyIR(ir),geometry:{operation:'tube-quadratic-control',action:'set',curve:declaration}});expect(a.receipt.unaffectedComponentsPreserved).toBe(true);expect(a.ir.components[1]).toEqual(ir.components[1]);expect(ir).toEqual(snapshot);validateAssemblyIR(a.ir);const b=await applyAssemblyComponentPatch(a.ir,{schema:'morphloom.component-patch/0.2',operationId:'clear',componentId:'rail',expectedInputFingerprint:a.receipt.outputFingerprint,geometry:{operation:'tube-quadratic-control',action:'clear'}});expect(b.ir).toEqual(ir);});
 it('rejects legacy new-op, stale/no-op, and atomically rejects a later invalid batch',async()=>{const ir=fixture(),snapshot=structuredClone(ir),hash=await fingerprintAssemblyIR(ir);const patch={schema:'morphloom.component-patch/0.2' as const,operationId:'bend',componentId:'rail',expectedInputFingerprint:hash,geometry:{operation:'tube-quadratic-control' as const,action:'set' as const,curve:declaration}};await expect(applyAssemblyComponentPatch(ir,{...patch,schema:'morphloom.component-patch/0.1'})).rejects.toThrow(/0.2/);const a=await applyAssemblyComponentPatch(ir,patch);await expect(applyAssemblyComponentPatch(a.ir,patch)).rejects.toThrow(/stale/);await expect(applyAssemblyComponentPatch(a.ir,{...patch,expectedInputFingerprint:a.receipt.outputFingerprint})).rejects.toThrow(/isolated/);await expect(applyAssemblyComponentBatchPatch(ir,{schema:'morphloom.component-batch-patch/0.2',operationId:'atomic',expectedInputFingerprint:hash,edits:[{componentId:'rail',geometry:patch.geometry},{componentId:'untouched',geometry:{operation:'tube-quadratic-control',action:'set',curve:{...declaration,controlPointMm:[0,0,0]}}}]})).rejects.toThrow(/quadratic|Bezier/);expect(ir).toEqual(snapshot);});
 it('revalidates existing endpoint deltas against the declared curve',async()=>{const ir=fixture();ir.components[0]!.geometry=migrateTubeQuadraticCurve(straight(),[100,40,0]);await expect(applyAssemblyComponentPatch(ir,{schema:'morphloom.component-patch/0.1',operationId:'bad-end',componentId:'rail',expectedInputFingerprint:await fingerprintAssemblyIR(ir),geometry:{operation:'tube-point-deltas',deltas:[{pointIndex:0,deltaMm:[100,40,0]}]}})).rejects.toThrow(/quadratic|Bezier/);});
 it('rejects missing deltas and batch attempts to override trusted patch fields',async()=>{const ir=fixture(),hash=await fingerprintAssemblyIR(ir);await expect(applyAssemblyComponentPatch(ir,{schema:'morphloom.component-patch/0.1',operationId:'bad-delta',componentId:'rail',expectedInputFingerprint:hash,geometry:{operation:'tube-point-deltas',deltas:[{pointIndex:0}]} } as never)).rejects.toThrow(/unsafe/);await expect(applyAssemblyComponentBatchPatch(ir,{schema:'morphloom.component-batch-patch/0.1',operationId:'override',expectedInputFingerprint:hash,edits:[{componentId:'rail',schema:'morphloom.component-patch/0.2',expectedInputFingerprint:hash,geometry:{operation:'tube-quadratic-control',action:'set',curve:declaration}}]} as never)).rejects.toThrow(/unsafe/);expect(ir).toEqual(fixture());});

 it('preserves legacy fractional coordinates bit-for-bit and samples actual generated rings/cap winding',()=>{const source=straight();source.points=[[.123456789,41.07022810274674,-41.89769011091261],[108.50000000000003,228.97377532084895,-55.0375129382]];const a=createTubePath(source),b=new THREE.CatmullRomCurve3(source.points.map(p=>new THREE.Vector3(p[0]/1000,p[1]/1000,p[2]/1000)),false,'centripetal');for(let i=0;i<=32;i++)expect(a.getPointAt(i/32).toArray()).toEqual(b.getPointAt(i/32).toArray());const curved=migrateTubeQuadraticCurve(straight(),[100,40,0]),g=compileAssemblyGeometry(curved),path=createTubePath(curved),p=g.getAttribute('position'),index=g.index!;try{for(let ring=0;ring<=32;ring++){const center=new THREE.Vector3();for(let j=0;j<12;j++)center.add(new THREE.Vector3().fromBufferAttribute(p,ring*13+j));center.divideScalar(12);expect(center.distanceTo(path.getPointAt(ring/32))*1000).toBeLessThan(.001);}for(const [start,t]of [[index.count-6,0],[index.count-3,1]]){const a=new THREE.Vector3().fromBufferAttribute(p,index.getX(start!)),b=new THREE.Vector3().fromBufferAttribute(p,index.getX(start!+1)),c=new THREE.Vector3().fromBufferAttribute(p,index.getX(start!+2)),normal=b.sub(a).cross(c.sub(a)).normalize();expect(normal.dot(path.getTangentAt(t!))*(t===0?-1:1)).toBeGreaterThan(.99);}}finally{g.dispose();}});

 it('rejects collapsed legacy tube edits without requiring a curve opt-in',async()=>{const ir=fixture(),hash=await fingerprintAssemblyIR(ir);await expect(applyAssemblyComponentPatch(ir,{schema:'morphloom.component-patch/0.1',operationId:'collapse',componentId:'rail',expectedInputFingerprint:hash,geometry:{operation:'tube-point-deltas',deltas:[{pointIndex:1,deltaMm:[-200,0,0]}]}})).rejects.toThrow(/Tube path/);expect(ir).toEqual(fixture());});

});
