import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';import {createHash} from 'node:crypto';import * as THREE from 'three';
import {compileAssemblyIR} from '../src/engine/assembly-compiler';import {LAUREL_HOMES_BUILDING_B_IR} from '../src/engine/laurel-homes-building-b';import type {AssemblyIR} from '../src/engine/assembly-ir';
const out=resolve(process.argv[2]),before=JSON.parse(readFileSync(resolve(process.argv[3]),'utf8'))as AssemblyIR;mkdirSync(out,{recursive:true});
const samples:{legacy:number[];candidate:number[]}={legacy:[],candidate:[]};let legacyHashes:Record<string,string>|undefined,candidateHashes:Record<string,string>|undefined;
for(let repeat=0;repeat<6;repeat++)for(const [key,ir]of [['legacy',before],['candidate',LAUREL_HOMES_BUILDING_B_IR]]as const){
 const start=performance.now(),build=compileAssemblyIR(ir,'beauty');if(repeat)samples[key].push(performance.now()-start);
 try{if(repeat===0){const hashes:Record<string,string>={};build.root.traverse(o=>{if(o instanceof THREE.Mesh){const h=createHash('sha256');for(const name of Object.keys(o.geometry.attributes).sort()){h.update(name);const a=o.geometry.getAttribute(name);h.update(Buffer.from(a.array.buffer,a.array.byteOffset,a.array.byteLength));}if(o.geometry.index){const a=o.geometry.index.array;h.update(Buffer.from(a.buffer,a.byteOffset,a.byteLength));}hashes[o.name]=h.digest('hex');}});if(key==='legacy')legacyHashes=hashes;else candidateHashes=hashes;}}
 finally{build.root.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});}
}
const median=(a:number[])=>[...a].sort((x,y)=>x-y)[2]!;const legacy=median(samples.legacy),candidate=median(samples.candidate);const geometryPreserved=JSON.stringify(legacyHashes)===JSON.stringify(candidateHashes);
const report={method:'five warm paired same-current-version compiles of frozen original IR and declared program; M5/Node24.13.1; own native/browser jobs closed',samples,legacyMedianMs:legacy,candidateMedianMs:candidate,ratio:candidate/legacy,geometryPreserved,meshCount:Object.keys(candidateHashes!).length,pass:geometryPreserved&&candidate<=2*legacy&&candidate<=10000,legacyHashes,candidateHashes};writeFileSync(resolve(out,'performance-and-preservation.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,candidateMedianMs:candidate,ratio:report.ratio,geometryPreserved,meshCount:report.meshCount}));if(!report.pass)throw Error('Frozen resource/geometry preservation budget exceeded');
