/** Raw GLB NORMAL versus raw GLB or bounded actual Blender-import samples. */
import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash}from'node:crypto';import * as T from'three';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';
const [beforeFile,afterFile,meshId,output,...delta]=process.argv.slice(2);assert(beforeFile&&afterFile&&meshId&&output&&!fs.existsSync(output),'before.glb after.glb|probe.json mesh-id new-report [after translation mm x y z]');assert(delta.length===0||delta.length===3);const translation=delta.length?delta.map(Number):[0,0,0];assert(translation.every(n=>Number.isFinite(n)&&Math.abs(n)<=1000));
const hash=(v:Uint8Array)=>createHash('sha256').update(v).digest('hex');type Samples={sha256:string;corners:number;points:Map<string,T.Vector3[]>;coordinates:Map<string,T.Vector3>;kind:string};const owned:T.Object3D[]=[];const key=(p:T.Vector3)=>[p.x,p.y,p.z].map(v=>Math.round(v*1e6)).join(',');
async function read(file:string,after:boolean):Promise<Samples>{
 const raw=fs.readFileSync(file);assert(raw.length<=256000000&&raw.length>12);
 const points=new Map<string,T.Vector3[]>(),coordinates=new Map<string,T.Vector3>();const add=(p:T.Vector3,n:T.Vector3)=>{assert([...p.toArray(),...n.toArray()].every(Number.isFinite)&&n.lengthSq()>0);if(after)p.sub(new T.Vector3(...translation.map(v=>v*.001) as [number,number,number]));const k=key(p);const previous=coordinates.get(k);assert(!previous||previous.distanceTo(p)<=1e-10,'Ambiguous coordinate bin; use a more precise contract');coordinates.set(k,p.clone());const rows=points.get(k)??[];rows.push(n.normalize());points.set(k,rows);};
 if(raw.subarray(0,4).toString()!=='glTF'){
  assert(raw.length<=20000000);const value=JSON.parse(raw.toString());assert(['morphloom.blender-import-normal-probe/0.1','morphloom.blender-import-normal-probe/0.2'].includes(value.schema)&&value.stableMeshId===meshId&&Array.isArray(value.samples)&&value.samples.length<=200000);assert(value.schema!=='morphloom.blender-import-normal-probe/0.2'||['NORMALS','FLAT','SMOOTH'].includes(value.importShading),'Unknown import policy');assert(value.sourceSha256===hash(fs.readFileSync(beforeFile)),'Probe is not bound to this actual GLB input');assert(value.coordinates==='glTF right-handed Y-up world; inverse Blender Z-up basis; meters','Probe coordinate contract mismatch');assert(Number.isInteger(value.corners)&&value.corners>0&&value.corners<=6000000,'Probe corner budget');assert(delta.length===0,'Probe coordinates already explicit; no guessed transform');for(const row of value.samples){assert(Array.isArray(row)&&row.length===6&&row.every((v:unknown)=>typeof v==='number'&&Number.isFinite(v)));add(new T.Vector3(...row.slice(0,3)),new T.Vector3(...row.slice(3)));}return{sha256:hash(raw),corners:value.corners,points,coordinates,kind:'actual Blender import samples'};
 }
 assert(raw.readUInt32LE(4)===2&&raw.readUInt32LE(8)===raw.length&&raw.readUInt32LE(16)===0x4e4f534a,'Invalid GLB framing');const jsonLength=raw.readUInt32LE(12);assert(jsonLength<=16000000&&20+jsonLength<=raw.length,'JSON budget');const document=JSON.parse(raw.subarray(20,20+jsonLength).toString());assert((document.nodes?.length??0)<=10000&&(document.meshes?.length??0)<=128&&(document.accessors?.length??0)<=1024,'Scene budget');assert(!(document.buffers??[]).some((v:{uri?:string})=>v.uri)&&!(document.images??[]).some((v:{uri?:string})=>v.uri),'External/URI dependencies unsupported; embedded GLB only');assert(!(document.nodes??[]).some((v:{skin?:number})=>v.skin!==undefined)&&!(document.animations??[]).length&&!(document.meshes??[]).some((v:{primitives:{targets?:unknown[]}[]})=>v.primitives.some(p=>p.targets?.length)),'Static normals only; skin/morph/time samples unsupported');
 const gltf=await new GLTFLoader().parseAsync(new Uint8Array(raw).buffer,'');owned.push(...gltf.scenes);gltf.scene.updateMatrixWorld(true);let mesh:T.Mesh|undefined;
 gltf.scene.traverse(o=>{if(!(o instanceof T.Mesh))return;const index=gltf.parser.associations.get(o)?.nodes,name=index===undefined?o.name:gltf.parser.json.nodes[index].name;if(name===meshId){assert(!mesh,'Ambiguous mesh ID');mesh=o;}});assert(mesh,'Actual mesh ID absent');const object=mesh as T.Mesh,g=object.geometry,p=g.getAttribute('position'),n=g.getAttribute('normal');assert(p&&n&&p.count===n.count&&p.count<=2000000);const normalMatrix=new T.Matrix3().getNormalMatrix(object.matrixWorld),count=g.index?.count??p.count;assert(count<=6000000);
 for(let i=0;i<count;i++){const index=g.index?g.index.getX(i):i;add(new T.Vector3().fromBufferAttribute(p,index).applyMatrix4(object.matrixWorld),new T.Vector3().fromBufferAttribute(n,index).applyMatrix3(normalMatrix));}return{sha256:hash(raw),corners:count,points,coordinates,kind:'actual GLB NORMAL accessor'};
}
try{
 const before=await read(beforeFile,false),after=await read(afterFile,true);assert(before.corners===after.corners,'Triangle corner count changed');assert(before.points.size===after.points.size,'Unique coordinate count changed');const matched=new Map<string,string>(),used=new Set<string>();let coordinateDriftMeters=0;
 for(const [k,p]of before.coordinates){const cell=k.split(',').map(Number),candidates=[];for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++){const other=[cell[0]+x,cell[1]+y,cell[2]+z].join(','),q=after.coordinates.get(other);if(q&&p.distanceTo(q)<=1e-6)candidates.push({key:other,distance:p.distanceTo(q)});}assert(candidates.length===1&&!used.has(candidates[0].key),'Missing/ambiguous explicit coordinate correspondence');matched.set(k,candidates[0].key);used.add(candidates[0].key);coordinateDriftMeters=Math.max(coordinateDriftMeters,candidates[0].distance);}
 let worst=0;let worstCoordinate='';let samples=0;
 for(const [coordinate,normals]of before.points){const current=after.points.get(matched.get(coordinate)!)!;for(const [a,b]of [[normals,current],[current,normals]])for(const n of a){const angular=Math.min(...b.map(other=>Math.acos(Math.min(1,Math.max(-1,n.dot(other))))*180/Math.PI));if(angular>worst){worst=angular;worstCoordinate=coordinate;}samples++;}}
 const report={schema:'morphloom.native-normal-payload-comparison/0.1',pass:worst<=.01,meshId,before:{sha256:before.sha256,kind:before.kind},after:{sha256:after.sha256,kind:after.kind},translationMm:translation,corners:before.corners,worldCoordinates:before.points.size,bidirectionalSamples:samples,coordinateToleranceMeters:1e-6,maxCoordinateDriftMeters:coordinateDriftMeters,maxNormalDifferenceDeg:worst,worstCoordinateMicrometers:worstCoordinate,fixedToleranceDeg:.01,scope:'Raw NORMAL payload or actual first-import normals; worst per selected mesh, no quality averaging or geometry regeneration'};fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(!report.pass)process.exitCode=1;
}finally{const geometries=new Set<T.BufferGeometry>(),materials=new Set<T.Material>(),textures=new Set<T.Texture>();for(const root of owned)root.traverse(o=>{if(o instanceof T.Mesh){geometries.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);for(const v of Object.values(m))if(v instanceof T.Texture)textures.add(v);}}});for(const g of geometries)g.dispose();for(const m of materials)m.dispose();for(const t of textures)t.dispose();}
