import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash}from'node:crypto';import * as T from 'three';import {GLTFExporter}from'three/addons/exporters/GLTFExporter.js';
import {generateBearingProject}from'../src/engine/bearing-pack';import {migrateElementProjectToV7,editPart,serializeProject}from'../src/engine/element-project';import {exportSelectedScene,ELEMENT_RENDERER_REVISION}from'../src/engine/element-renderer';import{analyzeTopology}from'../src/engine/topology';
const out=path.resolve(process.argv[2]);assert(!fs.existsSync(out));fs.mkdirSync(out,{recursive:true});const hash=(v:string|Uint8Array)=>createHash('sha256').update(v).digest('hex');class Reader{result:ArrayBuffer|null=null;onloadend:(()=>void)|null=null;readAsArrayBuffer(b:Blob):void{void b.arrayBuffer().then(v=>{this.result=v;this.onloadend?.();});}}Object.assign(globalThis,{FileReader:Reader});
const rows=[];
for(const [name,input]of [['default',{}],['small',{boreDiameterMm:12,outerDiameterMm:30,widthMm:10,ballDiameterMm:5,ballCount:7}],['large',{boreDiameterMm:40,outerDiameterMm:80,widthMm:24,ballDiameterMm:12,ballCount:12}]]as const){
 const before=migrateElementProjectToV7(generateBearingProject(input)),after=editPart(before,'inner_race',{normalWeighting:'corner-angle'}),snapshots=[],times:number[][]=[];
 for(const [variant,project]of [['before',before],['after',after]]as const){const ids=project.parts.map(p=>p.id),timings=[];for(let i=0;i<7;i++){const start=performance.now(),s=exportSelectedScene(project,ids);if(i>=2)timings.push(performance.now()-start);s.dispose();}times.push(timings);
 const s=exportSelectedScene(project,ids);try{assert(analyzeTopology(s.root).pass);s.root.updateMatrixWorld(true);const data=new Map<string,{normal:string;rest:string}>();s.root.traverse(o=>{if(!(o instanceof T.Mesh))return;const g=o.geometry,m=o.material as T.MeshStandardMaterial;data.set(o.name,{normal:hash(JSON.stringify(Array.from(g.getAttribute('normal').array))),rest:hash(JSON.stringify({attributes:Object.fromEntries(Object.entries(g.attributes).filter(([k])=>k!=='normal').map(([k,a])=>[k,{size:a.itemSize,values:Array.from(a.array)}])),index:g.index?Array.from(g.index.array):null,world:o.matrixWorld.toArray(),parent:o.parent?.name,color:m.color.toArray(),roughness:m.roughness,metalness:m.metalness}))});});snapshots.push(data);
 fs.writeFileSync(path.join(out,`${name}-${variant}.elements.json`),serializeProject(project));const bytes=new Uint8Array(await new GLTFExporter().parseAsync(s.root,{binary:true,onlyVisible:false})as ArrayBuffer);fs.writeFileSync(path.join(out,`${name}-${variant}.glb`),bytes);
 }finally{s.dispose();}}
 for(const [id,a]of snapshots[0]){const b=snapshots[1].get(id)!;assert.equal(a.rest,b.rest,id);if(id==='inner_race')assert.notEqual(a.normal,b.normal);else assert.equal(a.normal,b.normal,id);}
 const average=(v:number[])=>v.reduce((a,b)=>a+b,0)/v.length,ratio=average(times[1])/average(times[0]);assert(ratio<=2&&Math.max(...times.flat())<=10000,'Fixed performance budget');rows.push({name,unchangedMeshes:before.parts.length-1,target:'inner_race',onlyNormalChanged:true,timingMs:times,averageRatio:ratio,files:Object.fromEntries(['before','after'].flatMap(v=>['glb','elements.json'].map(ext=>{const f=`${name}-${v}.${ext}`;return[f,{sha256:hash(fs.readFileSync(path.join(out,f))),bytes:fs.statSync(path.join(out,f)).size}]})))});
}
fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify({pass:true,rendererRevision:ELEMENT_RENDERER_REVISION,environment:process.version+' '+process.platform+' '+process.arch,method:'actual generated buffers/material/world/parent + actual GLB bytes; two warmups/five measured compiles',rows},null,2)+'\n');console.log(JSON.stringify(rows,null,2));
