import fs from 'node:fs';import {NodeIO} from '@gltf-transform/core';import {inspectDepthQuality} from '../src/engine/depth-boundary';import type {DepthSurfaceSource} from '../src/engine/depth-surface';
const out=process.argv[2]??'outputs/depth-continuous-20261003/refined';const rows=[];
for(const name of fs.readdirSync(out).filter(f=>f.endsWith('.continuous.depth.json'))){
 const source:DepthSurfaceSource=JSON.parse(fs.readFileSync(out+'/'+name,'utf8')),document=await new NodeIO().read(out+'/'+name.replace('.depth.json','.glb')),primitive=document.getRoot().listMeshes()[0]!.listPrimitives()[0]!,p=primitive.getAttribute('POSITION')!.getArray()!,idx=primitive.getIndices()!.getArray()!,depths=new Float64Array(source.samples.length).fill(NaN),[left,right,bottom,top]=source.camera.frameMm;
 for(let i=0;i<idx.length;i+=3){const vertices=[idx[i]!,idx[i+1]!,idx[i+2]!].map(v=>[(p[v*3]!*1000-left)/(right-left)*source.width-.5,(top-p[v*3+1]!*1000)/(top-bottom)*source.height-.5,p[v*3+2]!*1000]);const [a,b,c]=vertices;const denominator=(b![1]!-c![1]!)*(a![0]!-c![0]!)+(c![0]!-b![0]!)*(a![1]!-c![1]!);if(Math.abs(denominator)<1e-15)continue;
  for(let y=Math.max(0,Math.ceil(Math.min(...vertices.map(v=>v[1]!))));y<=Math.min(source.height-1,Math.floor(Math.max(...vertices.map(v=>v[1]!))));y++)for(let x=Math.max(0,Math.ceil(Math.min(...vertices.map(v=>v[0]!))));x<=Math.min(source.width-1,Math.floor(Math.max(...vertices.map(v=>v[0]!))));x++){
   const u=((b![1]!-c![1]!)*(x-c![0]!)+(c![0]!-b![0]!)*(y-c![1]!))/denominator,v=((c![1]!-a![1]!)*(x-c![0]!)+(a![0]!-c![0]!)*(y-c![1]!))/denominator,w=1-u-v;if(Math.min(u,v,w)<-1e-9)continue;const depth=source.camera.cameraZMm-(u*a![2]!+v*b![2]!+w*c![2]!);depths[y*source.width+x]=depth;
  }
 }
 const missing=source.mask.reduce((n,m,i)=>n+(m===1&&!Number.isFinite(depths[i])?1:0),0);const q=missing?null:inspectDepthQuality(source,depths);const anchorErrors=[...source.calibration.fit,...source.calibration.validation,...(source.quality!.boundary.status==='declared'?source.quality!.boundary.anchors:[])].map(a=>Math.abs(depths[a.pixel]!-a.depthMm));rows.push({name,missingForegroundPixels:missing,maximumAnchorErrorMm:Math.max(...anchorErrors.filter(Number.isFinite)),meshQuality:q});console.log(name,'missing',missing,'anchorMax',Math.max(...anchorErrors.filter(Number.isFinite)),'boundaryPass',q?.boundary.status);
}
if(process.argv.includes('--require-pass')&&rows.some(row=>row.missingForegroundPixels||!row.meshQuality?.pass||row.maximumAnchorErrorMm>.001))throw new Error('Actual GLB projected mesh fails fixed .001mm depth/coverage validation.');
fs.writeFileSync(out+'/projected-mesh-audit.json',JSON.stringify({schema:'morphloom.projected-mesh-audit/0.1',source:'actual GLB Float32 triangle interpolation at original pixel centres',rows},null,2));
