import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {performance} from 'node:perf_hooks';
import * as THREE from 'three';import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {compileDepthSurface,migrateDepthSurfaceMeshing,type DepthSurfaceSource} from '../src/engine/depth-surface';
import {analyzeTopology} from '../src/engine/topology';import {inspectExportedUv} from '../src/engine/uv-delivery';import {validateGlbStandard} from '../src/engine/gltf-standard-validation';
class Reader{result:ArrayBuffer|null=null;onloadend:(()=>void)|null=null;readAsArrayBuffer(b:Blob){void b.arrayBuffer().then(v=>{this.result=v;this.onloadend?.();});}}Object.assign(globalThis,{FileReader:Reader});
const out=path.resolve(process.argv[2]??'outputs/depth-continuous-20261003'),base=path.resolve(process.argv[3]??'outputs/depth-boundary-20261003'),hash=(v:string|Uint8Array)=>createHash('sha256').update(v).digest('hex');fs.mkdirSync(out,{recursive:true});const rows=[];
function gridDeficit(g:THREE.BufferGeometry,r:number,cx:number,cy:number){const counts=new Map<string,{a:number;b:number;count:number}>(),idx=g.index!,p=g.attributes.position!;for(let i=0;i<idx.count;i+=3){const v=[idx.getX(i),idx.getX(i+1),idx.getX(i+2)];for(let e=0;e<3;e++){const a=v[e]!,b=v[(e+1)%3]!,key=a<b?`${a}:${b}`:`${b}:${a}`;const value=counts.get(key);if(value)value.count++;else counts.set(key,{a,b,count:1});}}let maximum=0;for(const e of counts.values())if(e.count===1){const x=(p.getX(e.a)+p.getX(e.b))*500-cx,y=(p.getY(e.a)+p.getY(e.b))*500-cy;maximum=Math.max(maximum,r-Math.hypot(x,y));}return maximum;}
function surfaceChecks(g:THREE.BufferGeometry,center:[number,number,number]){
 const p=g.attributes.position!,n=g.attributes.normal!,idx=g.index!,ids=new Map<string,number>(),canonical:number[]=[],edges=new Map<string,{a:number;b:number;count:number}>();
 for(let i=0;i<p.count;i++){const point=[p.getX(i)*1000-center[0],p.getY(i)*1000-center[1],p.getZ(i)*1000-center[2]],key=[p.getX(i),p.getY(i),p.getZ(i)].map(v=>Math.round(v*1e9)).join(':');if(!ids.has(key))ids.set(key,ids.size);canonical.push(ids.get(key)!);const v=new THREE.Vector3(...point).normalize(),normal=new THREE.Vector3(n.getX(i),n.getY(i),n.getZ(i));assert(Math.abs(normal.length()-1)<1e-5);assert(v.dot(normal)>.99999);}
 for(let i=0;i<idx.count;i+=3){const v=[0,1,2].map(k=>canonical[idx.getX(i+k)]!);for(let k=0;k<3;k++){const a=v[k]!,b=v[(k+1)%3]!,key=a<b?`${a}:${b}`:`${b}:${a}`;const e=edges.get(key);if(e)e.count++;else edges.set(key,{a,b,count:1});}}
 const graph=new Map<number,number[]>();for(const e of edges.values())if(e.count===1){for(const [a,b] of [[e.a,e.b],[e.b,e.a]]){if(!graph.has(a!))graph.set(a!,[]);graph.get(a!)!.push(b!);}}
 assert(graph.size>0);for(const neighbours of graph.values())assert.equal(neighbours.length,2);const seen=new Set<number>();let loops=0;for(const key of graph.keys())if(!seen.has(key)){loops++;const queue=[key];while(queue.length){const a=queue.pop()!;if(seen.has(a))continue;seen.add(a);queue.push(...graph.get(a)!);}}
 assert.equal(loops,1);return {boundaryLoops:loops,normalUnitAndRadial:true,weldToleranceMeters:1e-9};
}
for(const file of fs.readdirSync(path.join(base,'fixtures')).filter(n=>n.endsWith('.depth.json')).sort()){
 const before:DepthSurfaceSource=JSON.parse(fs.readFileSync(path.join(base,'fixtures',file),'utf8'));
 if(!before.primaryForm){const torus=migrateDepthSurfaceMeshing(before);torus.preview='declared-sphere-front';torus.primaryForm={schema:'morphloom.sphere-front-constraint/0.1',radiusMm:64,centerMm:[0,0,0],basis:'authored-fixture',centerFitToleranceMm:.001};torus.meshing={schema:'morphloom.depth-meshing/0.1',mode:'declared-sphere-front',maxSagittaMm:.02};assert.throws(()=>compileDepthSurface(torus,{diagnostic:true}),/silhouette/);continue;}
 const s=migrateDepthSurfaceMeshing(before);s.preview='declared-sphere-front';s.meshing={schema:'morphloom.depth-meshing/0.1',mode:'declared-sphere-front',maxSagittaMm:Math.min(.02,s.primaryForm!.radiusMm/3000)};
 for(const key of ['samples','mask','calibration','quality','primaryForm','imageSha256','rawFieldSha256'] as const)assert.deepEqual(s[key],before[key]);
 const originalProject=fs.readFileSync(path.join(base,'bearing.elements.json'));const saved=JSON.stringify(s),start=performance.now(),compiled=compileDepthSurface(s,{diagnostic:true}),compileMs=performance.now()-start;assert(compileMs<1000);assert.equal(JSON.stringify(s),saved);assert(compiled.report.candidate?.validationPass);assert(compiled.report.meshing);assert.equal(compiled.report.releaseAllowed,false);
 const surface=surfaceChecks(compiled.geometry,s.primaryForm!.centerMm);
 const grid=compileDepthSurface({...before,preview:'declared-sphere-front'},{diagnostic:true});const prior=gridDeficit(grid.geometry,before.primaryForm.radiusMm,before.primaryForm.centerMm[0],before.primaryForm.centerMm[1]);assert(compiled.report.meshing.maximumRimRadialDeficitMm<prior*.5);
 for(const mode of ['grid','continuous']){
  const c=mode==='grid'?grid:compiled,native=mode==='grid'?{...before,preview:'declared-sphere-front'}:s,name=s.id+'.'+mode,root=new THREE.Group();root.name='depth-reference';root.userData={purpose:'diagnostic',releaseAllowed:false,originalRepresentation:'relative-depth-field'};const material=new THREE.MeshStandardMaterial({color:'#a7a7a7',roughness:.75,side:THREE.DoubleSide}),mesh=new THREE.Mesh(c.geometry,material);mesh.name=s.id;root.add(mesh);
  try{const topology=analyzeTopology(root);assert.equal(topology.degenerateTriangles,0);assert.equal(topology.nonManifoldEdges,0);assert.equal(topology.selfIntersections,0);assert(topology.selfIntersectionComplete);assert(topology.boundaryEdges>0);
   const bytes=await new GLTFExporter().parseAsync(root,{binary:true}) as ArrayBuffer,standard=await validateGlbStandard(bytes),source=JSON.stringify(native),uv=await inspectExportedUv(bytes,source);assert.equal(standard.status,'pass');assert(uv.report.integrityPass);for(const m of uv.report.meshes)delete m.triangles;
   if(mode==='grid')assert.equal(hash(new Uint8Array(bytes)),hash(fs.readFileSync(path.join(base,s.id+'.candidate.glb'))));
   fs.writeFileSync(path.join(out,name+'.glb'),new Uint8Array(bytes));fs.writeFileSync(path.join(out,name+'.depth.json'),source);
   rows.push({name,mode,inputFixture:file,sourceSha256:hash(source),outputSha256:hash(new Uint8Array(bytes)),compileMs:mode==='continuous'?compileMs:null,...(mode==='continuous'?{surface}:{}),gridBoundaryDeficitMm:prior,report:c.report,topology,standard,uv});console.log(JSON.stringify({name,compileMs,priorBoundaryDeficitMm:prior,continuous:c.report.meshing,triangles:c.report.triangles}));
  }finally{material.dispose();}
 }
 for(const reject of ['hole','crop']){const invalid=structuredClone(s);if(reject==='hole'){const p=invalid.mask.findIndex((v,i)=>v===1&&!invalid.calibration.fit.some(a=>a.pixel===i)&&!invalid.calibration.validation.some(a=>a.pixel===i)&&!(invalid.quality?.boundary.status==='declared'&&invalid.quality.boundary.anchors.some(a=>a.pixel===i)));invalid.mask[p]=0;}else invalid.camera.frameMm[1]=0;assert.throws(()=>compileDepthSurface(invalid,{diagnostic:true}));}
 assert(originalProject.equals(fs.readFileSync(path.join(base,'bearing.elements.json'))));grid.geometry.dispose();compiled.geometry.dispose();
}
assert.equal(rows.filter(r=>r.mode==='continuous').length,5);fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify({schema:'morphloom.depth-continuous-evidence/0.1',rows,rawSourcesPreserved:true,priorBearingProjectUnchanged:true},null,2));
